config/routes.rb
Rails.application.routes.draw do
  get 'posts/new'

  post 'post_content', to: "posts#post_content"

  post 'comment_content', to: "comments#comment_content"

  get 'apps/index'

  get 'channels/index'

  resources :questions, only: [:show, :create]

  post 'sales/create'

  get 'sales/show'

  resources :services
  get 'prices/index'

  get 'prices/show'

  root   'welcome#index'

  get 'download_android_app', to: "apps#download_android_app"

  get 'download_kodi_addon', to: "apps#download_kodi_addon"

  get 'download_gse_iptv', to: "apps#download_gse_iptv"

  get 'download_stv_emulator', to: "apps#download_stv_emulator"

  resources :sessions, only: [:new, :create, :destroy]

    get '/logout' => "sessions#destroy"

  resources :users, except: [:destroy, :index]

  get '/:token/confirm_email/', :to => "users#confirm_email", as: 'confirm_email'

  resources :users do
    member do
      get :confirm_email
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  has_many :sales
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :service
  belongs_to :equipment
  belongs_to :user

  validates :amount, :zip, :state, :address, presence: true

  def self.process_stripe_payment(params, email)
    Stripe.api_key = Rails.application.secrets.stripe_secret_key
    amt = sprintf('%.2f', params[:total_amount])
    plan = "plan_#{amt}"
    card_token = Stripe::Token.create( :card => {
    	:name => params[:card_name],
    	:number => params[:card_number],
    	:exp_month => params[:exp_month],
    	:exp_year => params[:exp_year],
    	:cvc => params[:card_cvv] })

    customer_params = {:card => card_token[:id], :plan => plan, :email => email}

    stripe_customer = Stripe::Customer.create(customer_params)
    return true
  end

  def self.process_paypal_payment(params,email, return_path)
  	values = {
      business: email,
      cmd: '_xclick',
      upload: 1,
      notify_url: return_path,
      amount: params[:total_amount],
      quantity: '1',
      item_name: "Nitroplus",
      return: return_path
    }

    return "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
  end
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :sales
end

app/models/user.rb
class User < ApplicationRecord
has_many :questions
has_many :sales
has_many :posts
has_many :comments, through: :post, foreign_key: "comment_id"
has_many :services, through: :sales, foreign_key: "service_id"
has_many :equipments, through: :sales, foreign_key: "equipment_id"
validates_format_of :email, :with => /@/
before_create :confirmation_token
mount_uploader :picture, PictureUploader

  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true

  before_save :to_downcase

  has_secure_password

  def full_name
    first_name.capitalize + " " + last_name.capitalize
  end

  def to_downcase
    email.downcase!
  end

  def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    save!(:validate => false)
  end

  private

  def confirmation_token
    if self.confirm_token.blank?
       self.confirm_token = SecureRandom.urlsafe_base64.to_s
    end
  end

end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  def index

  end

  def download_android_app
  send_file "#{Rails.root}/app/assets/docs/nitro_android_app.apk", type: "application/apk", x_sendfile: true
  end

  def download_kodi_addon
  send_file "#{Rails.root}/app/assets/docs/nitro_kodi_addon.zip", type: "application/zip", x_sendfile: true
  end

  def download_gse_iptv
  send_file "#{Rails.root}/app/assets/docs/gse-iptv.apk", type: "application/apk", x_sendfile: true
  end

  def download_stv_emulator
  send_file "#{Rails.root}/app/assets/docs/STVEmulatorPro.apk", type: "application/apk", x_sendfile: true
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  end

  def post_content
    post = Post.new(post_params)
    user = User.find(params[:user_id])
    if post.save
      redirect_to user
    else
      redirect_to root_url
    end
  end
private
  def post_params
    params.permit(:content, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]



  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      @user.save(validate: false)
      UserMailer.registration_confirmation(@user).deliver
      redirect_to root_url, :flash => { alert: "Please confirm your email address, check your mailbox!" }


      # UserMailer.welcome_email(@user).deliver!
    else
      @errors = @user.errors.full_messages
      render :new
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = User.find(params[:id])
    @user.assign_attributes(user_params)
    if @user.save
      redirect_to @user
    else
      @errors = @user.errors.full_messages
      render @user
    end
  end

  def confirm_email
  @user = User.find_by_confirm_token(params[:id])
   if @user
     @user.email_activate
      redirect_to @user, :flash => { alert: "Welcome to the NitroPlus! Your email has been confirmed." }
   else
     redirect_to root_url, :flash => { error: "Sorry. User does not exist" }
   end
 end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/users/_form.html.erb
<div class="space-70"></div>

<div class="container">
     <div class="row">
         <div class="col-lg-6 offset-lg-3">
             <div class="my-login-form">
               <%= form_with(model: user, local: true) do |form| %>
                <% if user.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

                  <ul>
                    <% user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
                <% end %>
                 <h4 class="text-uppercase">Sign up</h4><hr>
                 <div class="row">
                   <div class="col-md-6 margin-btm-20">
                     <%= form.text_field :first_name, placeholder: 'first name', id: :user_first_name, class: "form-control" %>
                   </div>

                   <div class="col-md-6 margin-btm-20">
                     <%= form.text_field :last_name, placeholder: 'last name', id: :user_last_name, class: "form-control" %>
                   </div>

                   <div class="col-md-6 margin-btm-20">
                     <%= form.text_field :email, placeholder: 'email', id: :user_email, class: "form-control" %>
                   </div>

                   <div class="col-md-6 margin-btm-20">
                     <%= form.password_field :password, placeholder: 'password', id: :user_password, class: "form-control" %>
                   </div>

                   <div class=" col-md-12 text-center">
                     <%= form.submit class: "btn theme-btn-color" %>
                   </div>
                 <% end %>
                 </div>
                 <hr>
                 <div class="form-btm-link text-center">
                  <a href="signup.html">Already have an account? </a>
                 </div>
             </form>
             </div>
         </div>
     </div>
 </div>

app/views/users/edit.html.erb
<h1>Editing User</h1>



<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<section id="content-region-3" class="padding-40 page-tree-bg">
            <div class="container">
                <h3 class="page-tree-text">
                    Create an account
                </h3>
            </div>
</section>

<%= render 'form', user: @user %>

</br>
</br>

<!-- <%= link_to 'Back', users_path %> -->

app/views/users/show.html.erb
<div class="container">
  <div class="space-70"></div>

<div class="col-md-4">
  <div class="sidebar-box">
  </div>
  <div class="sidebar-box">
      <h4><%=@user.full_name%></h4>
      <% if @user.picture? %>
        <%= image_tag @user.picture.url, class: "img-fluid", size: "200x240"%>
      <% else %>
      <%=image_tag("avtar.png", class: "img-fluid", size: "150x200")%>
      <% end %>
      <%= form_for(@user) do |f| %>
        <span class="picture">
          <%= f.file_field :picture%>
        </span>
         <%= f.submit "upload avatar", class: "btn btn-outline-info" %>
      <% end %>
  </div><hr>
  <div class="sidebar-box">
      <h4>Current Information</h4>
       <p>First Name: <%= @user.first_name %></p>
       <p>Last Name: <%= @user.last_name %></p>
       <p>Email: <%= @user.email %></p>
       <%= link_to 'Edit', edit_user_path(@user) %>
  </div><hr>
  <div class="sidebar-box">
      <h4>User services</h4>
      <div class="recent">
        <h5> service information </h5>
        <% if @user.sales.first %>
          <p>Service type: <%= @user.services.first.name %></p>
        <% else %>
          <p> you dont have any NitroPlus services yet, try us out for free!</p>
          <%= link_to 'Services', services_path(@user) %>
        <% end %>
      </div>
  </div>
  <hr>
</div>
<div class="col-md-8">
  <% if current_user %>
  <h4 class="heading-mini">
        Ask any question or share your thoughts!
    </h4>
    <%= form_tag (post_content_path) do %>


          <div class="row">
              <div class="col-md-8 offset-md-2 product-information">
                <%= hidden_field_tag 'user_id', @user.id %>
              </div>
              <div class="col-md-12">
                  <%= text_area_tag :content, nil, placeholder: 'post...', class: "form-control", rows:'4'%>
              </div>
              <div class="col-md-12 text-right">
                  <%= submit_tag "Send post", class: "btn btn-outline-info" %>
              </div>
          </div>
      <% end %>
    <%end%>


              <div role="tabpanel" class="tab-pane"
               id="Reviews" aria-expanded="false">
                <% @user.posts.each do |post| %>
                  <ul class="reviews list-unstyled">
                      <li class="clearfix">
                          <span class="avtar">
                            <% if @user.picture? %>
                              <%= image_tag @user.picture.url, class: "img-circle", size: "80x50"%>
                            <% else %>
                            <%=image_tag("avtar.png", class: "img-circle", size: "80x80")%>
                            <% end %>
                          </span>
                          <div class="review-content">

                              <h4><%=@user.full_name%></h4>
                              <span class="time-review"><%=time_ago_in_words(post.created_at)%> ago </span>

                              <p>
                                <%= post.content %>
                              </p>
                              <% if logged_in? %>
                              <%= form_tag (comment_content_path) do %>
                                <div class="row">
                                <div class="col-md-8 offset-md-2 product-information">
                                  <%= hidden_field_tag 'post_id', post.id %>
                                </div>
                                <div class="col-md-6">
                                    <%= text_area_tag :body, nil, placeholder: 'comment on the post...', class: "form-control", rows:'1'%>
                                </div>
                                <div class="col-md-6 text-right">
                                    <%= submit_tag "Submit comment", class: "btn btn-outline-info" %>
                                </div>
                            </div>
                            <% end %>
                            <%end%>
                          </div>
                          <% post.comments.each do |comment| %>
                            <ul class="reviews list-unstyled">
                              <div class="col-md-6">
                              <li class="clearfix">
                                <span class="avtar">
                                  <% if @user.picture? %>
                                    <%= image_tag comment.post.user.picture.url, class: "img-circle", size: "40x40"%>
                                  <% else %>
                                    <%=image_tag("avtar.png", class: "img-circle", size: "40x40")%>
                                  <% end %>
                                  </span>
                                  <div class="review-content">
                                    <h4><%=@user.full_name%></h4>
                                    <span class="time-review"><%=time_ago_in_words(post.created_at)%> ago </span>

                                    <p>
                                      <%= comment.body %>
                                    </p>
                                </li>
                                <div>
                              </ul>
                          <% end %>
                      </li>
                  </ul>
                  <% end %>
                  <div class="space-30"></div>


                  </div>
              </div>
          </div>


      </div>

</div>
<div class="space-70"></div>




    <!-- <div class="points">
      <h4>875</h4>
      <p>Power Points</p>
    </div>
    <div class="deal">
      <h3>Latest Deal</h3>
      <img src="http://lorempixel.com/600/215" />

    </div> -->