config/routes.rb
Rails.application.routes.draw do
  get 'posts/new'

  post 'post_content', to: "posts#post_content"

  post 'comment_content', to: "comments#comment_content"

  get 'apps/index'

  get 'channels/index'

  resources :questions, only: [:show, :create]

  post 'sales/create'

  get 'sales/show'

  resources :services
  get 'prices/index'

  get 'prices/show'

  root   'welcome#index'

  get 'download_android_app', to: "apps#download_android_app"

  get 'download_kodi_addon', to: "apps#download_kodi_addon"

  get 'download_gse_iptv', to: "apps#download_gse_iptv"

  get 'download_stv_emulator', to: "apps#download_stv_emulator"

  resources :sessions, only: [:new, :create, :destroy]

    get '/logout' => "sessions#destroy"

  resources :users, except: [:destroy, :index]

  get '/:token/confirm_email/', :to => "users#confirm_email", as: 'confirm_email'

  resources :users do
    member do
      get :confirm_email
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  has_many :sales
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :service
  belongs_to :equipment
  belongs_to :user

  validates :amount, :zip, :state, :address, presence: true

  def self.process_stripe_payment(params, email)
    Stripe.api_key = Rails.application.secrets.stripe_secret_key
    amt = sprintf('%.2f', params[:total_amount])
    plan = "plan_#{amt}"
    card_token = Stripe::Token.create( :card => {
    	:name => params[:card_name],
    	:number => params[:card_number],
    	:exp_month => params[:exp_month],
    	:exp_year => params[:exp_year],
    	:cvc => params[:card_cvv] })

    customer_params = {:card => card_token[:id], :plan => plan, :email => email}

    stripe_customer = Stripe::Customer.create(customer_params)
    return true
  end

  def self.process_paypal_payment(params,email, return_path)
  	values = {
      business: email,
      cmd: '_xclick',
      upload: 1,
      notify_url: return_path,
      amount: params[:total_amount],
      quantity: '1',
      item_name: "Nitroplus",
      return: return_path
    }

    return "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
  end
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :sales
end

app/models/user.rb
class User < ApplicationRecord
has_many :questions
has_many :sales
has_many :posts
has_many :comments, through: :post, foreign_key: "comment_id"
has_many :services, through: :sales, foreign_key: "service_id"
has_many :equipments, through: :sales, foreign_key: "equipment_id"
validates_format_of :email, :with => /@/
before_create :confirmation_token
mount_uploader :picture, PictureUploader

  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true

  before_save :to_downcase

  has_secure_password

  def full_name
    first_name.capitalize + " " + last_name.capitalize
  end

  def to_downcase
    email.downcase!
  end

  def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    save!(:validate => false)
  end

  private

  def confirmation_token
    if self.confirm_token.blank?
       self.confirm_token = SecureRandom.urlsafe_base64.to_s
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/apps/index.html.erb
<div class="space-70"></div>
<div class="container">
<div class="space-40"></div>
               <div class="row">
                      <div class="col-md-4 margin-btm-20">
                   <div class="person-section">
                      <%=image_tag("nitroTV.jpg", class: "img-fluid", )%>
                       <div class="person-desc">
                           <h3>NitroPlus  Android App</h3>
                           <%= link_to "download", download_android_app_path %>
                       </div>
                   </div><!--person section end-->
               </div><!--person col end-->
               <div class="col-md-4 col-sm-6 margin-btm-20">
                   <div class="person-section">
                       <%=image_tag("nitroTV.jpg", class: "img-fluid", )%>
                       <div class="person-desc">
                           <h3>NitroPlus Kodi TV AddOn</h3>
                            <%= link_to "download", download_kodi_addon_path %>

                       </div>
                   </div><!--person section end-->
               </div><!--person col end-->
               <div class="col-md-4 col-sm-6 margin-btm-20">
                   <div class="person-section">
                       <%=image_tag("nitroTV.jpg", class: "img-fluid", )%>
                       <div class="person-desc">
                           <h3>GSE IPTV</h3>
                           <%= link_to "download", download_gse_iptv_path %>
                       </div>
                   </div><!--person section end-->
               </div>
             </div>
           </div><!--team 3 col end-->

    </div>
    <div class="space-70"></div>
    <div class="container">
    <div class="space-40"></div>
                   <div class="row">
                          <div class="col-md-4 margin-btm-20">
                       <div class="person-section">
                           <%=image_tag("nitroTV.jpg", class: "img-fluid", )%>
                           <div class="person-desc">
                               <h3>STV Emulator</h3>
                               <%= link_to "download", download_stv_emulator_path %>
                           </div>
                       </div><!--person section end-->
                   </div><!--person col end-->
                   <div class="col-md-4 col-sm-6 margin-btm-20">
                       <div class="person-section">
                           <%=image_tag("nitroTV.jpg", class: "img-fluid", )%>
                           <div class="person-desc">
                               <h3>Smart IPTV</h3>
                               <%= link_to "download", "http://siptv.eu/mylist/" %>
                           </div>
                       </div><!--person section end-->
                   </div><!--person col end-->
                   <div class="col-md-4 col-sm-6 margin-btm-20">
                       <div class="person-section">
                           <%=image_tag("nitroTV.jpg", class: "img-fluid", )%>
                           <div class="person-desc">
                               <h3>IP Televions on Google Play</h3>

                               <%= link_to "download", "https://play.google.com/store/apps/details?id=com.paolorossignoli.iptv&hl=en" %>
                           </div>
                       </div><!--person section end-->
                   </div>
                 </div>
               </div><!--team 3 col end-->

        </div><!--Our team page end-->
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Nitroplus</title>

   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', 'animate', 'flexslider', 'jquery.mCustomScrollbar', 'magnific-popup', 'master-slider-custom', 'sweetalert', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'jquery.min', 'wow.min', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


        <%= render partial: 'partials/top_bar' %>

        <%= render partial: 'partials/navbar' %>

        <%= render partial: 'partials/flash_messages' %>

          <%= yield %>

        <%= render partial: 'partials/footer' %>



        <script src="https://www.paypalobjects.com/api/checkout.js"></script>



  </body>
</html>

app/views/partials/_flash_messages.html.erb
<% if !flash.empty? %>
  <div class="alert">
    <a href="" class="close">x</a>
    <% flash.each do |key, value| %>
      <%if value.kind_of?(Array) %>
        <%value.each do |error| %>
          <%=content_tag(:p, error, :class => "error") %>
          <% end %>
      <% else %>
        <%= content_tag(:p, value, :class => "flash") %>
        <%end%>
    <% end %>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<div id="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-4 margin-btm-20">
                <div class="footer-col">
                    <h3>NitroPlus</h3>
                    <p>
                        The newest and the best IPTV service available. Better quality, channel line up, and menu.. It blows away all the competition..
                    </p>
                    <p>
                      we Accept PayPal, and stripe
                    </p>
                </div>
                <div class="space-20"></div>
                <div class="footer-col">
                    <h3>contact info</h3>
                    <p><i class="ion-iphone"></i> +91 9887568614 WhatsApp</p>
                    <p><i class="ion-email"></i> www.nitroplus.us@gmail.com</p>
                </div>
                <div class="space-20"></div>

            </div><!--col-4 end-->
            <div class="col-md-3 margin-btm-20">

            </div><!--latest post col end-->
            <div class="col-md-5">
                <div class="footer-col">
                    <h3>Get in touch</h3>
                  <%= form_tag (questions_path) do %>


                        <div class="row">
                            <div class="col-md-6">
                              <%= text_field_tag :name, nil, placeholder: 'name..', class: "form-control" %>
                            </div>
                            <div class="col-md-6">
                                <%= text_field_tag :email, nil, placeholder: 'email..', class: "form-control" %>
                            </div>
                            <div class="col-md-12">
                                <%= text_field_tag :subject, nil, placeholder: 'Subject..', class: "form-control" %>
                            </div>
                            <div class="col-md-12">
                                <%= text_area_tag :message, nil, placeholder: 'Massage...', class: "form-control", rows:'7'%>
                            </div>
                            <div class="col-md-12 text-right">
                                <%= submit_tag "Send massege", class: "btn btn-lg btn-white" %>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div><!--get in touch col end-->
        </div><!--footer main row end-->
        <div class="space-70"></div>
        <div class="row">
            <div class="col-md-12 text-center footer-bottom">
                <!-- <a href="index.html"> <img src="logo-white.png" alt=""></a> -->
                <div class="space-20"></div>
                <span>&copy;2017. All right resrved. Design by Veleda</span>
            </div>
        </div><!--footer copyright row end-->
    </div><!--container-->

app/views/partials/_navbar.html.erb
        <nav class="navbar navbar-toggleable-sm navbar-light bg-faded yamm">
            <div class="container">
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="/"><%=image_tag("NitroPlus_logo2.png", class: "img-fluid", size: "100x140")%></a>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="nav navbar-nav ml-auto">
                        <li class="active  nav-item">
                            <%= link_to "Home", root_path, class: "-toggle nav-link" %>
                        </li>
                        <li class=" nav-item">
                            <%= link_to "Buy now", services_path, class: "-toggle nav-link" %>

                        </li>
                        <li class="  nav-item">
                            <%= link_to "Channels", channels_index_path, class: "-toggle nav-link" %>
                        </li>
                        <!--mega menu-->
                        <li class=" -fw nav-item">
                            <%= link_to "Apps", apps_index_path, class: "-toggle nav-link" %>
                          </li>

                        <!--menu Features li end here-->

                        <!-- <li class="social-nav nav-item"><a href="#" class="nav-link"><i class="ion-social-facebook"></i></a></li>
                        <li class="social-nav nav-item"><a href="#" class="nav-link"><i class="ion-social-twitter"></i></a></li>
                        <li class="social-nav nav-item"><a href="#" class="nav-link"><i class="ion-social-youtube"></i></a></li> -->
                    </ul>
                </div>
            </div>
        </nav>

app/views/partials/_top_bar.html.erb
<div class="top-bar">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 hidden-md-down">
                <ul class="info list-inline pull-left hidden-sm-down">
                    <li class="list-inline-item"><a href="#" class="hover-color"><i class="ion-ios-email-outline"></i> www.nitroplus.us@gmail.com</a></li>
                    <li class="list-inline-item"><i class="ion-iphone"></i> +91 (123) 456 78 90</li>
                </ul>
            </div>
            <div class="col-lg-8">
                <div class="text-right">
                    <ul class="info list-inline">
                      <%if logged_in?%>
                        <li class="list-inline-item"><a href="/users/<%=current_user.id%>" class="hover-color list-inline-item"><%=current_user.full_name%></a></li>
                        <li class="list-inline-item"><a href="/logout">Logout</a></li>
                      <%else%>
                        <li class="list-inline-item"><a href="/users/new" class="hover-color list-inline-item">Create an account?</a></li>
                        <li class="list-inline-item"><a href="/sessions/new" class="hover-color list-inline-item"> Login</a></li>
                      <%end%>
                        <!-- <li class="dropdown list-inline-item"><a href="#" data-toggle="dropdown" class="dropdown-toggle hover-color" aria-expanded="false"> Eng.</a>
                            <ul class="dropdown-menu dropdown-menu-right lang-dropdown">
                                <li><a href="#">ENGLISH</a></li>
                                <li><a href="#">FRANCE</a></li>
                                <li><a href="#">GERMANY</a></li>
                                <li><a href="#">JAPANESE</a></li>
                            </ul>
                        </li> -->
                        <li class="list-inline-item">
                            <div class="right-search">
                                <span class="icon-search">
                                    <i class="ion-ios-search-strong"></i>
                                </span>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>


    </div>
  </div>